nathanj/spirit-island-pbp

- pbf/models.py
Powerstorm's threshold requires 3 Air, not 3 Animal...
> Fix threshold on Powerstorm.

- bot.py
Looks like this emoji was removed and replaced with a lighter colored icon a few months ago, around 2023-12-05
Example of the broken emoji failing to render:
https://discord.com/channels/846580409050857493/1213505829404413963/1214016733669625866
Autocomplete showing the new emoji name:
Note I haven't tested this in any way!
> Switch to new Trickster emoji name

- pbf/models.py
- pbf/templates/game.html
- pbf/views.py
Before this commit, the host has no choice, so colours are randomly
selected.
If specific colours are desired, then they have to ask an admin to
change the colours after the spirit is added.
Wouldn't it be nice to be able to specify the colour when adding the
spirit and not have to bother an admin?
---
A significant decision to be made is how two cases should be handled:
* a valid colour is submitted, but it is already in use
* a nonexistent or otherwise invalid colour is submitted
Right now these are all handled by simply randomly assigning the colour, but it may be more useful to show an error instead.
---
~~I'm still setting up my Python install so I haven't tested this yet. I would like to to fulfill my responsibility as a submitter, but I won't be offended if I'm beaten to the …
> allow selecting colour when adding a spirit

- bot.py
The correct fix for #24; tested by copying messages from the PBP log and running them through the `adjust_msg` regex w/o `emoji_to_discord_map` (since my Discord bot isn't attached to the SI server).
💙 worked w/o changes; :heart: failed to match before changes, works after changes.
> Fix posting red spirit logs to Discord

- pbf/views.py
put the logic immediately after the presence is setup on the board for the newly created spirit
tested base Serpent and the Locus aspect after this change; don't see any other aspects needing this change
> remove 1st presence from top track for Serpent Locus aspect

- pbf/templates/game.html
Intended purpose:
A player can now add #ss2 to the page URL to scroll to screenshot 2. This is useful in games where the host puts the island in screenshot 2 (and a number of hosts do, in fact, do this).
There's not as much point in adding #ss1 to scroll to the first image, but it feels like it should be there for consistency?
This feature is currently unannounced/unadvertised. Players only know about it if they inspect the HTML or read this commit message. Not yet decided how to spread knowledge of it.
Abbreviations ss1 and ss2 instead of screenshot1 and screenshot2 because at this moment these would only be used by a player manually typing `#ss2`, so there is a benefit in keeping it short.
> add IDs to the two screenshots

- pbf/views.py
By not sending the cards to the discard if there are 5 cards remaining in the selection, players can just click gain on the two cards they want.
Before this code change, gaining their first choice will send the selection to the discard, and then the player must gain the second out of the discard, This works but is a poor experience.
> choose_card: streamline Boon of Reimagining

- pbf/models.py
- pbf/templates/energy.html
Helps remind the player that they've taken the action and shouldn't take the opposite one (but doesn't actually block them from doing so, in case they misclick)
> Show prepared/added this turn indicators for Unconstrained Fangs

- pbf/templates/game.html
- pbf/views.py
closes https://github.com/nathanj/spirit-island-pbp/issues/60 if the Apocrypha category and Exploratory Testing category are sufficiently clear that these spirits are set apart from the rest.
---
It can be a little cryptic to only show one word of the name, and for
some spirits it's not clear which word I should look for
For example:
* Fractured Days Split the Sky: Fractured or Days?
* Shifting Memory of Ages: Shifting or Memory?
* Shroud of Silent Mist: Mist or Shroud?
By showing the full name, there is no longer any question.
Disadvantage: the dropdown does get quite wide.
> group spirits by expansion and show their full names in spirit dropdown

- pbf/templates/game.html
- pbf/views.py
saves a few extra steps per player when setting up the game
> allow setting player name when adding a spirit

- island/urls.py
- pbf/templates/player.html
- pbf/views.py
Sometimes players accidentally hit the button and then need an admin's help to reshuffle the cards back in the deck.
This change will let them do it themselves.
It is assumed that players will only use this when they genuinely made a mistake rather than to cheat on their card gains.
This doesn't help if someone accidentally hit the Take 1 button though, since then the card goes right to their hand instead of to the selection. Something else will be needed for that case.
> allow players to undo gaining cards

- pbf/models.py
Closes https://github.com/nathanj/spirit-island-pbp/issues/51
Priority here is to be clear to the players. I would think that combining the elements and card plays into one checkmark/X indicator is too confusing. So what about separate indicators for each?
Note that I've checked two other digital implementations of Dances Up Earthquakes' spirit panel, and neither of them show a checkmark for card plays (both of them show one checkmark only, for the elements only) so being the only implementation that shows one for card plays carries additional risk of being confusing via unfamiliarity.
> GamePlayer#thresholds: check Dances Up Earthquakes' played cards

- pbf/tests.py
- pbf/views.py
Removes Boon of Vigor from Sunshine River's starting hand per the aspect's instructions.
Closes #65
> Remove Boon of Vigor from Sunshine River

- pbf/management/commands/seeddb.py
We'll not perform a migration because apparently someone has already modified the card in production and so no migration is needed. This is just correcting the record for anyone who seeds the database.
Closes https://github.com/nathanj/spirit-island-pbp/issues/96
> seeddb: Add Animal element to Incite the Mob card

- pbf/models.py
- pbf/views.py
Previous behaviour:
* Dark Fire was using permanent elements, which I didn't like because a player may decrement it.
* Intensify didn't have its permanent element at all
Intentionally no migration. Just having everyone currently playing them adjust manually.
> GamePlayer: use elements to give Dark Fire and Intensify their permanent moon

- pbf/api.py
my intent is to have the GET /api/game/{uuid} endpoint give the complete information about the game state, such that (if it should ever be necessary) a game can fully be reconstructed by using the data from that endpoint.
(It won't have the images, but I leave that to individual games' hosts)
> api: show complete information about a game

- island/settings.py
otherwise, the commands in the README will error with a KeyError on EXTRA_ALLOWED_HOSTS
> island/settings: Make EXTRA_ALLOWED_HOSTS optional

- pbf/models.py
removing available colours using a set (rather than a `for` loop) isn't just for flashier code; it actually has a subtle behaviour change for duplicate colours.
Before this change, using the admin interface to set two players to the same colour causes `available_colors` to crash, as `remove` does when removing a nonexistent element. This means the game cannot be loaded.
However, it's my opinion that if an admin *really* wants to do this, they should be allowed to do so (at their own risk), without causing the game to be unloadable. It's discouraged because it may be confusing to the players, but a more graceful response than crashing is called for if it so happens.
We still will not allow duplicate colours to be assigned in the UI, because it's confusing and unlikely to desired most of …
> don't crash if players have the same colour

- pbf/templates/game.html
- pbf/templates/player.html
closes https://github.com/nathanj/spirit-island-pbp/issues/41 (in conjunction with an upcoming change that will remove them from the host draw buttons)
> show deck size on "Show deck" buttons

- pbf/views.py
Selecting either Roiling Waters or Serene Waters will clear all other healing cards.
Selecting either Waters Renew or Waters Taste of Ruin will clear the other.
Previously if you misclicked there was no way to undo your mistake.
In particular:
If you try to select both Roiling and Serene Waters, Serene Waters always appeared on top and covered Roiling Waters.
If you try to select both Waters Renew and Taste of Ruin, both innates would appear, but thresholds were for Waters Renew only; Waters Taste of Ruin was ignored and in fact kept shwing the indicators for Swirl and Spill.
> choose_healing_card: add ability to change healing cards

- pbf/templates/game.html
- pbf/templates/player.html
- pbf/templates/power_deck.html
This seems sensible because then operations related to the decks are all in one place.
Closes https://github.com/nathanj/spirit-island-pbp/issues/141
> move show deck buttons next to gain power buttons

- island/urls.py
- pbf/templates/game.html
- pbf/templates/player.html
- pbf/tests.py
- pbf/views.py
This allows individual players to bookmark the URL for their own spirit and always be directed to their appropriate tab when visiting that URL.
Partial solution to
https://github.com/nathanj/spirit-island-pbp/issues/102
A full solution would involve cookies of some sort, but this is an easy-to-implement partial solution for now.
> add direct link to a spirit tab

- bot.py
Together, these help debug errors when setting up and running a new instance of the bot.
It also allows the bot to attempt to follow the game even if pinning failed, e.g. if a guild intentionally denies the bot the ability to pin messages.
closes https://github.com/nathanj/spirit-island-pbp/issues/36
> notify of errors on $follow: errors when pinning, invalid URL

- pbf/templates/player.html
All other forget buttons have this confirmation, so this matches the experience.
It's relatively rare to forget from impending anyway. You can only do it to gain a major, not to pay for an aided by element event.
> templates/player: add confirmation to forget from impending

- pbf/views.py
you don't need these when rendering energy.html, energy.html doesn't read anything that compute_card_thresholds changes (the _cards variables, nor computed_thresholds)
> remove unneeded calls to compute_card_thresholds

- pbf/templates/player.html
- pbf/views.py
Otherwise, players don't know whether they've reached the thresholds.
Since https://github.com/nathanj/spirit-island-pbp/pull/31 this has become more important.
Before that change, the card would move from the impending area to the play area, where the indicators would be shown.
However, now they stay in the impending area, so there is no opportunity to see the indicators.
> show threshold check/x on impending cards

- pbf/api.py
otherwise, deployments where the bot attempts to invoke the API via the IPv6 ::1 would fail, as `ipaddress.IPv4Address` would fail to parse it
> api: support IPv6 in the allowed list

- pbf/static/pbf/sipbp.css
- pbf/templates/base.html
This allows browsers to cache this file which doesn't change, and means we no longer have to send this content with every single request.
However, this change is pretty low impact. A full page load is expected to be a few megabytes, and this is about a 1 kilobyte savings, so it's less than 0.1%.
> move base template style to css file

- bot.py
must have accidentally left them in from when the format string didn't start with "send"
> bot: remove extraneous f from fake-discord outputs

- bot.py
we're awaiting the `create_task` and this particular task `logger` loops forever, so we would never get to that line
> bot: move diagnostic "we have logged in" message before the await

- bot.py
This helps bot owners when setting up initially, where a possible error
is that the API isn't set up to authorise the bot.
> bot: notify of failure to link game, don't say "now relaying" unless it succeeded 

- island/settings.py
- poetry.lock
- pyproject.toml
Each game only keeps its two current screenshots; as soon as a new screenshot is loaded, the old files are orphaned.
Rather than leaving these orphaned files around, we should delete them to save space.
It's safe to do this as we don't need to keep any files for archival purposes; the files would have also been sent to the game channel.
> install django-cleanup to clean old screenshots

- pbf/static/pbf/sipbp.css
- pbf/templates/game.html
Avoids accidentally invoking the functionality when unintended while hopefully still being convenient.
> discard top N powers: default to 0, add button for # of players, use radio instead of select

- .env.template
- README.md
- island/urls.py
- pbf/views.py
want to remove all doubt about the intention of this endpoint and remove any chance that it accidentally gets called in production
> island/urls: Only add view_screenshot in DEBUG

- .env.template
- bot.py
This allows the bot to safely listen to messages in discussion channels
without accidentally seeing a topic change in those channels as a
request to send game updates to them.
> bot: support ignoring topic changes in non-update channels

- pbf/templates/player.html
the parts for threshold achieved and not achieved differeed only in the img src, so it's better to make it clearer to the reader that that is the only way they differ, rather than force the reader to manually compare the two lines to make sure of this.
This change isn't just being made capriciously. I soon need to make some changes to these marks, and deduplicating the common portions halves the number of places where changes need to be made.
> templates/player: deduplicate common parts of thresholds

- poetry.lock
- pyproject.toml
Do the following dependency updates:
* Upgrade Pillow to version 11 (current version) because version 9 does not work with Python 3.13+
* Update the base required version of Python to 3.9 because that's what Pillow version 11 requires as a min version (and it's been almost 5 years...)
* Add audioop-lts if using python 3.13+ because the discord bot depends on it and it was deprecated and removed post-Python 3.12
Also got rid of the annoying dev-dependencies warning.
Closes #130 
Closes #89
> Update some dependencies

- poetry.lock
https://github.com/python/tzdata/releases
Test plan:
Run the site and confirm that it runs.
May need to specifically run on Windows for the test to be decisive, as Django has a `sys_platform == "win32"` marker on their dependency on this.
> update indirect dependency tzdata 2024.1 -> 2025.2

- .env.template
It doesn't seem to make sense to advise the use of * unless the administrator has made sure this makes sense for their environment.
This also helps administrators understand what kind of value should be put in this field: just the hostname, and not the protocol.
> .env.template: Give example si.bitcrafter.net for EXTRA_ALLOWED_HOSTS

- bot.py
This would have been happening since using django_cleanup, in 225228f00292dafd1ac05247136c6b3de22c2d3e a part of  https://github.com/nathanj/spirit-island-pbp/pull/166
> bot: Don't crash on a FileNotFound

- pbf/tests.py
- pbf/views.py
This incurs fewer database queries. It's a noticeable speedup when reshuffling the minor or major power decks, but we'll apply it everywhere for consistency.
> add_player: move all cards at once

- pbf/tests.py
- pbf/views.py
This incurs fewer database queries. It's a noticeable speedup when reshuffling the minor or major power decks, but we'll apply it everywhere for consistency.
> reclaim_all: move all cards at once

- pbf/tests.py
- pbf/views.py
this shouldn't actually happen because its only caller, card_from_deck, will already reject invalid deck type, but we should e consistent in applying this enforcement and apply it in both places instead of only one.
---
moving all cards at once makes reshuffle noticeably faster
> reshuffle_discard: reject an invalid deck type; move all cards at once

- pbf/tests.py
Noticed (with help from a coverage checker) that this case was missing in tests.
> TestMatchSpirit: test that base spirit name can refer to its aspect

- pbf/models.py
- pbf/tests.py
Before this PR, a player view for a just-created spirit (four card hand) makes eight queries for in-play cards and nine queries for presences.
After this PR, the same player view makes three queries for in-play cards and two queries for presences.
See individual commit messages for the breakdown of improvements
> GamePlayer: make elements and presences_off_track cached_property

- pbf/views.py
`first().id` loads the entire model, which is unnecessary because we only need the ID.
https://docs.djangoproject.com/en/5.2/ref/models/querysets/ explains that `first()` is one of the methods that doesn't return a `QuerySet`.
Instead, we should use `values_list` which creates a `QuerySet` that will return just the specified fields when evaluated.
This allows us to remove the unnecessary `exists()` query as well, since `first()` will return `None` if there are no matches, which is exactly the semantics we want, because that will cause us to try to use the next search criterion. Previously `first().id` would crash because of the `.id` lookup on a `None`.
> try_match_spirit: Only query for the ID, not other values

- pbf/models.py
- pbf/templates/game.html
- pbf/templates/setup.html
- pbf/templates/tabs.html
- pbf/views.py
We only need the full info of the player whose spirit panel we are actively showing. For all other players, we only need just enough info to display their tab.
Queries before this commit:
* one to check whether there are any players
* one (full info, unnecessary) to get the ID of the first player to show their tab
* three to count the number of players:
* one to check if it's non-zero to decide whether to show tabs
* two for the discard N cards from deck button
* one to show the full info of the current tab's player
* one (full info, unnecessary) to show the tab list
Queries after this commit:
* one to count the number of players
* one to get the ID of the first player to show their tab
* one to show the full info of the current tab's player
* one (summary) to show the tab list
Two …
> Game: provide player summary property

- pbf/models.py
Full accounting:
This was originally consistently misspelled everywhere as Resilence:
https://github.com/nathanj/spirit-island-pbp/commit/fcb940029e5a3fec9e9b03cc2dd825a05f3f7c1b 2022-02-06 (spirit)
https://github.com/nathanj/spirit-island-pbp/commit/c555715fa4dd0743a3add024d9ec5acf15730d49 2022-09-30 (thresholds)
this means everything worked because everything was using the same wrong spelling.
However, then when I reorganised spirits by expansion, I used the
correct spelling, not realising that it was previously incorrect:
https://github.com/nathanj/spirit-island-pbp/commit/086a539fe3c5bcdd4832399b8388fc2d513a0bd2 2024-09-28
https://github.com/nathanj/spirit-island-pbp/pull/61
At this point Resilience no longer has its aspect card image nor thresholds.
I discovered later on that the …
> models: fix Resilience Earth's thresholds (misspelled as Resilence)

- pbf/views.py
return_to_deck was added in c94624427aa351e2cfd8f00dce76640f149ecbde but no log message was added at that time.
Other actions that interact with the discard pile have since added logging:
Forget: b931cf331cf460289af5196cfc7a4c590cad0d29
Regain: 7a4a494f858023f04f22d9706e6e4b76ffb87495
Adding logging to returning to deck seems most consistent and helps everyone understand where a card might have gone.
> return_to_deck: add log message

- pbf/static/pbf/spirit-icon-Exploratory Bringer.png
this should have been removed alongside the rest of the exploratory Bringer materials in ea09430c6590dd45aef2419be8e6941c44643a19
> remove spirit icon for Exploratory Bringer

- pbf/views.py
helps track where cards went and improves visibility of Days That Never Were to all players, aiding team turn planning.
> create_days: send log message with the card images

- pbf/templates/player.html
It's not necessary to do it. Either there are cards (in which case we need to show them and the count is unnecessary), or there aren't (in which case a query trying to select them will not really perform any worse than one trying to count them)
> templates/player: Don't make a separate days_ordered.count query

- pbf/templates/player.html
a list is truthy if and only if it's non-empty, so this has the same effect and saves a database query.
> templates/player: replace selection.count with just selection_cards

- pbf/models.py
- pbf/templates/player.html
- pbf/views.py
player.html pretty much requires compute_card_thresholds to function properly, otherwise the player's in-play cards, hand, and selection aren't shown.
Before this commit, if you ever render player.html, the author writing the calling view has to remember to call compute_card_thresholds. This undocumented requirement is a stumbling block and potential point of confusion.
Instead, we should have player.html always compute the information it needs, without any additional calls needed in the view.
> templates/player: automatically compute thresholds

- README.md
As of 2025-08-20, Discord has added Pin Messages as a new permission.
Manage Messages will still work until 2026-01-12, but we should not wait until the last minute to update the documentation.
https://discord.com/developers/docs/change-log?topic=HTTP+API#pin-permission-split
> README: use Pin Messages, not Manage Messages

- pbf/tests.py
- pbf/views.py
Otherwise, cards in the previous selection will disappear from the game and no longer be accessible.
We already enforced this in the UI, but now this adds the same check server-side.
A player might accidentally do this if they have multiple tabs open to the same game, or in the case of a slow network.
> don't set a selection if the player already has one active

- pbf/templates/player.html
Otherwise, it's hard to tell where one ends and the other begins
> templates/player: separate the options with commas

- pbf/admin.py
This is not a supported operation. If you do this, it doesn't change either of these things:
* cards in hand
* presence
this leads to an inconsistent state that isn't representative of any spirit at all.
To avoid any impression that it's a supported operation, disable it.
> admin: disable editing spirit

- pbf/tests.py
- pbf/views.py
opacity will be defaulted to its starting value. energy/elements will be checked against whether it's expected to be empty
> import_game: allow imported presence to omit opacity/energy/elements
