nathanj/spirit-island-pbp

- pbf/models.py
- pbf/views.py
Adds support for Dark Fire Shadows aspect.
Includes support to treat moon/fire interchangeably as well as the additional starting card. The only missing thing is the image for the aspect, I haven't looked into that, yet.
> Aspect shadows darkfire

- pbf/templates/game.html
- pbf/templates/player.html
Sometimes players want to know what the odds are of seeing a card in their next gain.
> show number of cards in major/minor decks

- .env.template
- .gitignore
- README.md
- bot.py
- island/settings.py
- pbf/api.py
- pbf/tests.py
- poetry.lock
- pyproject.toml
- requirements.txt
- bot.py dependencies are not all listed, added them to poetry.lock
- Add instructions to env.template
- Add more environment variables to modify for not using si.bitcrafter.net exactly (and similar)
- Remove aioredis from bot.py and add redis as an alternative
> Update bot.py requirements and add support for more environment variables

- pbf/models.py
6 uniques
16 minors
Unquenchable Flames already had its threshold added Growth Through Sacrifice has a threshold, but I did not bother adding it since usual users of the site are no longer able to acquire a copy.
Closes https://github.com/nathanj/spirit-island-pbp/issues/25
> add thresholds for unique and minor powers

- pbf/models.py
the previous order doesn't really have any rhyme or reason to it
> available_colors: Arrange in rainbow order

- pbf/models.py
- pbf/templates/game.html
- pbf/views.py
Doesn't work in all browsers, but I think whether it works for a particular browser is beyond this project's ability to control.
closes https://github.com/nathanj/spirit-island-pbp/issues/118 ... if it would work
> templates/game: Show colours in the dropdown

- island/urls.py
- pbf/models.py
- pbf/templates/color.html
- pbf/templates/game.html
- pbf/templates/player.html
- pbf/views.py
Previously you needed an admin for this. Now anyone can do it.
> add UI to reassign player colours

- island/urls.py
- pbf/api.py
- pbf/migrations/0046_earthquake_presence_impending.py
- pbf/migrations/0047_impending_this_turn.py
- pbf/models.py
- pbf/templates/player.html
- pbf/tests.py
- pbf/views.py
Closes https://github.com/nathanj/spirit-island-pbp/issues/52
>  Dances Up Earthquakes: add + to all impending button

- island/urls.py
- pbf/models.py
- pbf/templates/discard_pile.html
- pbf/views.py
Allows undoing accidental takes/host draws
Also allows undoing a gain if they've already selected a card
> add ability to return a card from discard to deck

- pbf/views.py
closes https://github.com/nathanj/spirit-island-pbp/issues/58
> take_power: Show image of the taken power

- pbf/templates/discard_pile.html
- pbf/views.py
Adds a log message when someone claims a power from the power discard pile.
Fix for #95
> Log when a card is retrieved from the power discard pile

- pbf/templates/game.html
- pbf/views.py
if someone visits a page with a spirit spec and uploads an image, we want to keep them on the spirit they selected.
> add_screeenshot: preserve spirit spec

- pbf/models.py
- pbf/templates/player.html
- pbf/tests.py
- pbf/views.py
closes https://github.com/nathanj/spirit-island-pbp/issues/75
> adjust Dances Up Earthquakes' impending card costs in Blitz

- bot.py
allow testing the Redis components without a Discord token
> bot: Add fake Discord

- .env.template
- README.md
closes https://github.com/nathanj/spirit-island-pbp/issues/33
> README: explain the role of DEBUG in serving static files locally

- README.md
Closes https://github.com/nathanj/spirit-island-pbp/issues/34
> README: Add documentation of running a bot

- island/settings.py
these were recommended by `poetry run python manage.py check --deploy` and by https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
> set SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE to true if DEBUG is off

- pbf/templates/game.html
- pbf/views.py
More convenient than having to select a file, submit the form, select the second file, submit the form
> allow uploading two files at once

- island/urls.py
- pbf/static/pbf/import-help.html
- pbf/templates/index.html
- pbf/tests.py
- pbf/views.py
This will import a game that was exported from the `api/game/<uuid>` endpoint, or constructed using the same syntax.
This allows:
* transferring games between instances of the site
* recovering from data loss events
* creating a game with some initial conditions (such as Destiny Unfolds)
> add game importer

- bot.py
Lately duplicate messages have been sent. We do not know the cause.
We can apply the short-term solution of dropping the duplicate messages, but this is not a good long-term solution because it does nothing to attempt to find and fix the root of the problem.
> bot: drop duplicate messages

- bot.py
Should have been done with 199b2e4fbeded32f9bf52165cedd9d9ab6cdba48 and e64fda651dfd886ec96eea484dc440f99e5de59f
> fake discord: Handle client.user and client.guilds

- bot.py
This should stop the bot from trying to send duplicate messages.
Closes https://github.com/nathanj/spirit-island-pbp/issues/183
> bot: Create only one relay task

- README.md
This has been reported to happen on older versions of Poetry.
> README: Add note about poetry keyring error

- pbf/views.py
shorter and clearer way of saying the same thing, and makes clear that we're not further relying on the list to remain shuffled afterward
> add_player: Use random.choice instead of random.shuffle

- pbf/models.py
Main motivation is to be able to perform these calculations with just a NamedTuple of energy and elements, rather than a full Presence model object (as we don't need position, etc.)
> models: in-line most calculations based on presence 

- pbf/views.py
This issues one query to update them all at once rather than one query for each individual player
> edit_players: bulk update players

- pbf/models.py
- pbf/static/pbf/sipbp.css
- pbf/templates/tabs.html
Allows us to tell at a glance who is and isn't ready without having to go through everyone's tab one by one.
> templates/tabs: Show the spirit's name in bold if they're ready

- pbf/views.py
we were otherwise making one query per card
> compute_card_thresholds: prefetch impending cards

- README.md
- bot.py
Closes https://github.com/nathanj/spirit-island-pbp/issues/199
> bot: Add rename command to rename the channel

- pbf/models.py
- pbf/templates/energy.html
- pbf/templates/energy_and_spirit_resource.html
- pbf/templates/player.html
- pbf/templates/spirit_specific_resource.html
- pbf/views.py
Usually these two do not depend on each other and do not need to be rendered together.
The only exception is Spreading Rot Renews the Earth.
> render energy and spirit-specific resource independently

- pbf/views.py
it's sensible to show the new message that's added by the host draw
> add log trigger (reload logs) on a host draw

- pbf/tests.py
- pbf/views.py
we were doing this in five places, and it makes sense to deduplicate.
> add_log_msg: deduplicate common code to show names/images of cards; deduplicate player colour and spirit
